### ISSUE TITLE
Be able to tell if a character is fullwidth

### ISSUE THREAD

**Issue by sotojuan** [Qqwy/elixir-unicode#2]
As mentioned [here](https://elixirforum.com/t/proposal-be-able-to-tell-if-a-character-is-fullwidth/1789/2).

A friend of mine has an [implementation of this in JavaScript](https://github.com/sindresorhus/is-fullwidth-code-point/blob/master/index.js) and I've successfully ported it and the tests for it to an Elixir project of mine. It just checks for Unicode codepoint ranges.

It's not pretty, but it works. If you know if a more Elixir-y way to implement this, let me know, if not I can make a a PR.

**Comment by Qqwy** [comment]
I apologize for taking so long to get back to you.

This would be a great addition to the package. 
The given JavaScript code can be translated 1:1 to Elixir. The only change that would make it more pretty in Elixir is to use character literals like `?a` instead of the hexadecimals.

Thank you for this great suggestion :smile: . Please go ahead and open a Pull Request.

**Comment by Qqwy** [comment]
Actually, if we port that JavaScript code, we write something that will need to change every time the Unicode standard is modified. It might be a better idea to find out how we can see if a chacter is full width or half width from the .txt files with character information that the Unicode Consortium exports, so we can just recompile the script with the new .txt file when things change.

I will look into this.

**Comment by Qqwy** [comment]
It was hard to find. The proper file that is programmatically created for each new version is [EastAsianWidth.txt, AKA data11](http://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt). More information [here](http://www.unicode.org/reports/tr11/tr11-31.html#Classifications).

It seems that this file has character ranges, followed by one of the following identifiers:
- F East Asian Fullwidth: Wide characters, can be converted to a narrow form.
- H East Asian Halfwidth: Implicitly wide but unmarked, can be converted to a narrow form. 
- W for wide: These chars are always wide, do not have a narrow form.
- Na for Narrow: These characters are narrow, and have an explicit Fullwidth or Halfwidth form.
- N for neutral. (Not East Asian). Most other characters that are not usually used in East Asian languages.
- A for Ambiguous: Might be Fullwidth or Halfwidth, depending on context.

![Venn diagram with 5/6 groups, taken from above guide.](http://www.unicode.org/reports/tr11/images/tr11.h1.jpg)

---

So, it seems that while it is now relatively easy to give each character one of above properties, it still is hard to tell 'if a character is fullwidth', as this sometimes depends on the context.

@sotojuan , do you have any advice? My experience with any of the East Asian character sets is limited to distinguishing Shōgi pieces, I'm afraid :sweat_smile: .

**Comment by sotojuan** [comment]
Whoop, super late reply. I'm afraid I have no idea how to resolve te ambiguity. All I know about characters comes from that original JS file 😓
