### ISSUE TITLE
Get the visual width of a string

### ISSUE THREAD

**Issue by sotojuan** [Qqwy/elixir-unicode#3]
The visual width calculates the width of each character (see #2) and returns an appropriate number.

For example: `"abcde"` has width 5, but `"古池や"` has width 6 as some of its characters are fullwidth.

The calculation takes a string and uses `reduce` with a function that checks for width and adds `+ 1` or `+ 2` appropriately to an initial state of 0.

The reason is this is useful is for CLI apps. Say I wanted to make a box with text centered or aligned to the right: I need to know how wide the actual text is so I can align it properly.

**Comment by Qqwy** [comment]
This is a great idea.

Am I correct in the assumption that this is mostly useful when working with monospace fonts? In those fonts, most characters are half-width, except some larger characters, right?

**Comment by sotojuan** [comment]
I think it's useful for any fonts but it's especially useful in terminal-related stuff!

Also this is blocked by #2 because we'd use that to tell if a character is fullwidth.
